version: "3"
services:
  colouring-london:
    container_name: colouring-london
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://dockeruser:postgres@postgres-colouring-london:5432/colouringlondon
      NODE_ENV: development
      PORT: 8080
      APP_COOKIE_SECRET: 123456
    ports:
      - "8080:8080"
  db:
    container_name: postgres-colouring-london
    image: ubuntu/postgres:12-20.04_beta
    ports:
      - "5432:5432"
    volumes: 
      - ./postgresdata:/var/lib/postgresql/data
      - ./colouring-london/migrations:/colouring-london/migrations
      - ./colouring-london/etl:/colouring-london/etl
      - ./colouring-london/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    restart: always
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: colouringlondon